export const HUNGARY_SWIM_LOCATIONS = [
  'Duna Aréna, Budapest',
  'Hajós Alfréd Nemzeti Sportuszoda, Budapest',
  'Tüske Uszoda, Budapest',
  'BVSC Uszoda, Budapest',
  'Kőér utcai Uszoda, Budapest',
  'Császár-Komjádi Sportuszoda, Budapest',
  'Kőbánya Sport Club Uszoda, Budapest',
  'Szent Gellért Sportuszoda, Budapest',
  'Debreceni Sportuszoda, Debrecen',
  'Gyarmati Dezső Sportuszoda, Miskolc',
  'Bitskey Aladár Uszoda, Eger',
  'Városi Sportuszoda, Győr',
  'Tófürdő és Fedett Uszoda, Szombathely',
  'Veszprém Uszoda, Veszprém',
  'Virágfürdő Kaposvár',
  'Szegedi Sportuszoda, Szeged',
  'Hódmezővásárhelyi Gyarmati Dezső Sportuszoda',
  'Soproni Lővér Uszoda',
  'Kecskeméti Fürdő',
  'Pécsi Hullámfürdő',
]